compile: &defaults
  image: buty4649/mruby-cli:3.1.0-focal
  volumes:
    - .:/home/mruby/code:rw
    - ./build:/opt/mruby/build
  command: rake compile
test:
  <<: *defaults
  command: rake test
bintest:
  <<: *defaults
  command: rake test:bintest
mtest:
  <<: *defaults
  command: rake test:mtest
clean:
  <<: *defaults
  command: rake clean
shell:
  <<: *defaults
  command: bash
release:
  <<: *defaults
  command: rake release
package:
  <<: *defaults
  command: rake package
